"""W3R-0 — arrival-range fold-to-bet-by-size measurement harness.

Spec:    docs/ai-dlc/specs/persona-realism-w3r-0.md
Tickets: docs/ai-dlc/tickets/persona-realism-w3r-0.md

WHY THIS EXISTS (the gap it closes)
-----------------------------------
The existing `fold_by_size` fixture (`tests/test_personas_postflop.py:455`)
measures fold-to-bet over a UNIFORM random deck — air-heavy, so it can only
prove slope/direction, never the archetype ABSOLUTE bands (station overbet
18–40%, fish 60–80%). Those §5 keystone magnitudes are gated nowhere. This
harness measures fold-rate over each persona's REALISTIC arrival range —
the hands it actually reaches the street with, generated by replaying its own
preflop (and street) policy — so W3R-2 can hard-prove the fish/station dial
fits rather than only their direction.

WHAT IT DOES (measurement only — ZERO bot behavior change)
----------------------------------------------------------
1. Arrival range (T1): canonical HU single-raised pot. Villain = RFI raiser,
   bot = `vs_rfi` caller/defender. Deal hands, replay `sample_preflop_action`
   per persona, keep ONLY the hands the persona flat-CALLS (3bet/raise hands
   EXCLUDED — a 3bettor is the aggressor and would be c-BETTING, not facing a
   c-bet, so counting them pollutes a single-raised-pot range and shifts the
   very bands we gate). That kept set is the flop arrival range.
2. Flop fold-to-bet (T2): fold-rate over the flop arrival range at
   {0.33, 0.5, 1.0, 1.5}× pot (mirrors `PRICE_FRACS`), paired + seed-pinned.
3. Turn/river continuation (T3): a scripted 2-player continuation sim (villain
   c-bets a fixed 2/3-pot each street; the bot responds) derives the turn then
   river CALL-continuing range, then measures fold-to-bet at the same buckets.
   Turn/river are MEASUREMENT-ONLY (no grounded absolute band yet).
4. Flop target bands (T4): grounded §5/F10 magnitudes as module constants +
   parametrized assertions — LIVE since W3R-2 fitted the fish/station dials
   (they shipped `pytest.mark.skip`-ed at W3R-0).

Everything is a PURE ADD: `sample_preflop_action` / `sample_postflop_decision`
are replayed READ-ONLY, no engine/JSON/conftest edits, no fixture re-records.

MANUAL INSPECTION
-----------------
Run:  cd backend && python -m tests.test_arrival_range_ftc
(or, inside a REPL, `print_curves()`) to dump the per-persona × street × size
fold curves. Pre-W3R-2 this showed the two leaks the T4 bands gate: the calling
station ~FLAT across sizes (size-blind) and the passive fish UNDER-folding the
overbet. Post-W3R-2 both rows rise across sizes inside the T4 bands.
"""

from __future__ import annotations

import functools
import random

import pytest

from app.domain.archetypes import VillainType
from app.domain.content.notation import hole_cards_to_class
from app.domain.equity import RANKS
from app.domain.personas import load_persona_packs, sample_preflop_action
from app.domain.personas_postflop import sample_postflop_decision
from app.domain.spot import ActionType, LegalAction, Position, Street

ALL_PERSONAS = sorted(v.value for v in VillainType)

# Mirror `test_personas_postflop.py::PRICE_FRACS` — one size per RES-E bucket
# (SMALL / MEDIUM / LARGE(pot) / OVERBET).
FLOP_FRACS = (0.33, 0.5, 1.0, 1.5)

# Sample size for the arrival sampler. >= the existing `_PRICE_N` (1250);
# bumped because the arrival filter is a SUBSET of the dealt spots and tight
# ranges (nit) keep only a sliver — the W3R-2 provability criterion is that the
# flop bands assert stably at this N across repeated seeds.
_ARRIVAL_N = 2500

# Canonical single-raised HU pot: RFI to 3bb, one flat call → ~6bb flop pot,
# each player ~97bb behind (100bb − 3bb preflop). The villain c-bets a FIXED
# 2/3-pot on every street to drive the continuation sim (T3).
_POT_FLOP = 6.0
_STACK_START = 97.0
_CONT_FRAC = 0.66

_DEAL_SEED = 20260721  # mirror the existing fixture's deal seed
# Position is a no-op for `vs_rfi` (all packs' nodes are `positions=None`
# wildcards) — the load-bearing setup is `facing="vs_rfi"` + the caller role.
_CALLER_POS = Position.BB


# --------------------------------------------------------------- legal helpers
# Local one-liners (no cross-import of the sibling test module's helpers).


def _lf() -> LegalAction:
    return LegalAction(action=ActionType.FOLD)


def _lc(amount: float) -> LegalAction:
    return LegalAction(action=ActionType.CALL, min_bb=amount)


def _lr(lo: float, hi: float) -> LegalAction:
    return LegalAction(action=ActionType.RAISE, min_bb=lo, max_bb=hi)


# --------------------------------------------------------------- spot dealing


def _deal_spots(n: int) -> list[tuple[tuple[str, str], list[str]]]:
    """Seed-pinned list of (hole, 5-card board). Same physical cards are reused
    across persona × size × street so range-composition variance cancels
    (paired sampling), exactly like the existing `fold_by_size` fixture."""
    deal_rng = random.Random(_DEAL_SEED)
    deck0 = [r + s for r in RANKS for s in "shdc"]
    spots = []
    for _ in range(n):
        deck = deck0[:]
        deal_rng.shuffle(deck)
        spots.append(((deck[0], deck[1]), deck[2:7]))  # hole + flop/turn/river
    return spots


# --------------------------------------------------------------- arrival ranges

Spot = tuple[tuple[str, str], list[str]]


class _Arrival:
    """Per-persona arrival ranges + the pure-3bet class set (for the call-only
    proof) + the per-street pot/stack the continuation sim resolves to."""

    def __init__(self) -> None:
        self.flop: dict[str, list[Spot]] = {}
        self.turn: dict[str, list[Spot]] = {}
        self.river: dict[str, list[Spot]] = {}
        self.pure_3bet_classes: dict[str, frozenset[str]] = {}
        # Uniform per-street pot/stack (call-only continuation on a uniform
        # starting pot ⇒ every continuing spot shares one trajectory).
        bet_f = round(_CONT_FRAC * _POT_FLOP, 2)
        self.pot_turn = _POT_FLOP + 2 * bet_f
        self.stack_turn = _STACK_START - bet_f
        bet_t = round(_CONT_FRAC * self.pot_turn, 2)
        self.pot_river = self.pot_turn + 2 * bet_t
        self.stack_river = self.stack_turn - bet_t


def _build_flop_arrival(pack, spots: list[Spot]) -> tuple[list[Spot], frozenset[str]]:
    """Replay the persona's `vs_rfi` preflop policy; keep flat-CALL hands only.

    Returns (kept spots, pure-3bet classes) where a pure-3bet class was observed
    raising (3bet/4bet/5bet) and NEVER calling — the call-only proof asserts
    those never leak into the arrival range.
    """
    rng = random.Random(999)
    kept: list[Spot] = []
    call_classes: set[str] = set()
    raise_classes: set[str] = set()
    for hole, board in spots:
        act = sample_preflop_action(pack, _CALLER_POS, "vs_rfi", hole, rng)
        cls = hole_cards_to_class(*hole)
        if act.name == "call":
            kept.append((hole, board))
            call_classes.add(cls)
        elif act.name in ("3bet", "4bet", "5bet_shove"):
            raise_classes.add(cls)
    return kept, frozenset(raise_classes - call_classes)


def _continues_call(pack, rng, hole, board_n, pot_pre, stack, street) -> bool:
    """True iff the persona flat-CALLS a fixed 2/3-pot c-bet on `board_n`.

    Continuation is CALL-ONLY by the same logic that makes the arrival range
    call-only (T1): a hand that RAISES becomes the aggressor and would be
    c-betting the next street, not facing a bet — counting it would pollute the
    DEFENDING range this harness measures. FOLD and RAISE both drop out.
    """
    bet = round(_CONT_FRAC * pot_pre, 2)
    d = sample_postflop_decision(
        pack, hole, board_n, [_lf(), _lc(bet), _lr(2 * bet, stack)],
        pot_pre + bet, stack, 1, rng, current_bet_to=bet, street=street,
    )
    return d.action is ActionType.CALL


@pytest.fixture(scope="module")
def arrival() -> _Arrival:
    packs = load_persona_packs()
    if set(VillainType) - set(packs):
        pytest.skip("not all persona packs authored yet")
    spots = _deal_spots(_ARRIVAL_N)
    a = _Arrival()
    for persona in ALL_PERSONAS:
        pack = packs[VillainType(persona)]
        flop, pure3 = _build_flop_arrival(pack, spots)
        a.flop[persona] = flop
        a.pure_3bet_classes[persona] = pure3
        # Turn range: flop arrivals that flat-call the flop c-bet.
        rng = random.Random(4001)
        turn = [
            s for s in flop
            if _continues_call(pack, rng, s[0], s[1][:3], _POT_FLOP, _STACK_START, Street.FLOP)
        ]
        a.turn[persona] = turn
        # River range: turn arrivals that flat-call the turn c-bet.
        rng = random.Random(4002)
        river = [
            s for s in turn
            if _continues_call(pack, rng, s[0], s[1][:4], a.pot_turn, a.stack_turn, Street.TURN)
        ]
        a.river[persona] = river
    return a


# --------------------------------------------------------------- fold curves


def _fold_curve(pack, spots, board_slice, pot_pre, stack, street, seed):
    """persona fold-to-bet over `spots` at each FLOP_FRACS size. Paired +
    seed-pinned (per-size seed) so cross-size comparisons are noise-stable."""
    out: dict[float, float] = {}
    for fi, frac in enumerate(FLOP_FRACS):
        to_call = round(frac * pot_pre, 2)
        pot = pot_pre + to_call
        legal = [_lf(), _lc(to_call), _lr(2 * to_call, stack)]
        rng = random.Random(seed + fi)
        folds = sum(
            sample_postflop_decision(
                pack, hole, board[:board_slice], legal, pot, stack, 1, rng,
                current_bet_to=to_call, street=street,
            ).action is ActionType.FOLD
            for hole, board in spots
        )
        out[frac] = folds / len(spots) if spots else float("nan")
    return out


@pytest.fixture(scope="module")
def fold_curves(arrival):
    """persona -> {'flop'|'turn'|'river': {frac: fold-rate}} over the persona's
    own arrival/continuation range at each street."""
    packs = load_persona_packs()
    curves: dict[str, dict[str, dict[float, float]]] = {}
    for persona in ALL_PERSONAS:
        pack = packs[VillainType(persona)]
        curves[persona] = {
            "flop": _fold_curve(
                pack, arrival.flop[persona], 3, _POT_FLOP, _STACK_START, Street.FLOP, 20260721
            ),
            "turn": _fold_curve(
                pack, arrival.turn[persona], 4, arrival.pot_turn, arrival.stack_turn,
                Street.TURN, 5000,
            ),
            "river": _fold_curve(
                pack, arrival.river[persona], 5, arrival.pot_river, arrival.stack_river,
                Street.RIVER, 6000,
            ),
        }
    return curves


# =====================================================================
# T1 — arrival-range builder (replay preflop policy, CALL-ONLY)
# =====================================================================


def test_t1_sample_size_at_least_price_n():
    # Done-condition (c): fixed N >= the existing `_PRICE_N` (1250).
    assert _ARRIVAL_N >= 1250


def test_t1_arrival_ranges_persona_ordered_by_tightness(arrival):
    """Done-condition (a): arrival ranges are persona-ordered by tightness —
    nit ⊂ (roughly) tag ⊂ maniac. Measured by kept-count: over the SAME dealt
    spots, a tighter preflop flat-calling range reaches the flop with strictly
    fewer hands. (A literal class-SUBSET is intentionally NOT asserted — nit
    and tag flat-call genuinely different STYLES, e.g. nit flats medium pairs
    the tag 3bets and vice-versa, so the ranges differ in composition, not just
    width; kept-count is the faithful tightness signal.) The maniac's range is
    the widest, containing the most classes."""
    n_nit = len(arrival.flop["nit"])
    n_tag = len(arrival.flop["tag"])
    n_maniac = len(arrival.flop["maniac"])
    assert n_nit < n_tag < n_maniac, (n_nit, n_tag, n_maniac)

    def n_classes(p):
        return len({hole_cards_to_class(*h) for h, _ in arrival.flop[p]})

    assert n_classes("nit") < n_classes("maniac"), (n_classes("nit"), n_classes("maniac"))


@pytest.mark.parametrize("persona", ALL_PERSONAS)
def test_t1_arrival_is_call_only_no_3bet_hands(arrival, persona):
    """Done-condition (b): the call-only proof — no hand class the persona
    3bets vs an RFI (pure-3bet: observed raising, never calling) appears in its
    arrival range."""
    arrival_classes = {hole_cards_to_class(*h) for h, _ in arrival.flop[persona]}
    assert arrival_classes.isdisjoint(arrival.pure_3bet_classes[persona]), (
        f"{persona}: 3bet hands leaked into arrival range: "
        f"{arrival_classes & arrival.pure_3bet_classes[persona]}"
    )


# =====================================================================
# T2 — flop fold-to-bet-by-size over the arrival range
# =====================================================================


def test_t2_flop_curve_produced_for_all_personas(fold_curves):
    """Smoke test: a flop fold-rate curve at every FLOP_FRACS size is produced
    for all 6 personas, with every rate a valid probability in [0, 1]."""
    for persona in ALL_PERSONAS:
        flop = fold_curves[persona]["flop"]
        assert set(flop) == set(FLOP_FRACS), (persona, flop)
        for frac, rate in flop.items():
            assert 0.0 <= rate <= 1.0, (persona, frac, rate)


# =====================================================================
# T3 — turn + river continuation ranges + fold-to-bet (measurement-only)
# =====================================================================


@pytest.mark.parametrize("street", ["turn", "river"])
def test_t3_continuation_curve_produced_for_all_personas(fold_curves, arrival, street):
    """Smoke test: the scripted continuation sim yields a turn AND river fold
    curve for all 6 personas (measurement-only — NO hard band; turn/river
    absolute magnitudes are not grounded yet)."""
    ranges = arrival.turn if street == "turn" else arrival.river
    for persona in ALL_PERSONAS:
        curve = fold_curves[persona][street]
        assert set(curve) == set(FLOP_FRACS), (persona, street, curve)
        # Continuation ranges are non-empty for every persona at the pinned N.
        assert ranges[persona], f"{persona} {street} continuation range empty"
        for frac, rate in curve.items():
            assert 0.0 <= rate <= 1.0, (persona, street, frac, rate)


# =====================================================================
# T4 — grounded FLOP target bands (LIVE since W3R-2)
# =====================================================================
#
# Absolute fold-to-bet bands grounded in the persona-realism audit §5 / F10
# (docs/ai-dlc/research/persona-realism-audit-2026-07-24.md). W3R-0 landed
# them `pytest.mark.skip`-ed because the bot leaked (station size-blind/flat,
# fish under-folding the overbet) — the whole reason W3R-2 existed.
#
# UN-SKIPPED at W3R-2 (persona-realism-w3r-2, 2026-07-24): the fitted dials are
# station `size_elasticity` 0.0→0.55 + `call_looseness` 4.0, fish
# `call_looseness` 0.42 (`size_elasticity` 1.3 owner-locked). Measured on this
# harness at the fitted dials (n_arrival station 1370 / fish 1037):
#   calling_station  0.33:0.095  0.5:0.134  1.0:0.177  1.5:0.220
#   passive_fish     0.33:0.206  0.5:0.361  1.0:0.511  1.5:0.638
# Owner INCLUDED the fish SMALL band (20–38%) as a live gate so the pair of
# fish bands gates the SLOPE, not just the ceiling. Only personas the audit
# grounds get a hard band; the rest stay measurement-only (curves emitted, no
# assertion). Turn/river: no hard band (magnitudes not grounded).
#
# (persona, frac, lo, hi, audit-source)
FLOP_BANDS = [
    # station — audit §5: shallow-but-positive slope. SMALL fold 3–15% ...
    ("calling_station", 0.33, 0.03, 0.15, "audit §5 station SMALL"),
    # ... rising to OVERBET fold 18–40% (a price response, not the flat leak).
    ("calling_station", 1.5, 0.18, 0.40, "audit §5 station OVERBET"),
    # passive_fish — audit §5/F10: steep fit-or-fold. SMALL fold 20–38%
    # (owner-INCLUDED at W3R-2 — the two-point curve gates the slope) ...
    ("passive_fish", 0.33, 0.20, 0.38, "audit §5/F10 fish SMALL"),
    # ... rising to OVERBET fold 60–80%.
    ("passive_fish", 1.5, 0.60, 0.80, "audit §5/F10 fish OVERBET"),
]


# ------------------------------------------------- stable-sample escalation (R1)
#
# N-DRAWLOOSE ruling R1 (2026-08-04, owner): the R10-TAIL-a1 remedy — escalate
# to a stable sample BEFORE failing. Precedent, followed here rather than
# re-invented: `test_personas_postflop.py:5704-5722` (the fold-to-cbet leg),
# where the cheap throughput reading is the first pass and only a breach pays
# for the large-n re-measure.
#
# WHY THIS BAND NEEDS IT. Each rate is a Monte-Carlo count over the persona's
# arrival range — ~1045 spots for the fish at `_ARRIVAL_N`, so SE ≈ 0.012
# against a margin of only 0.0077 over the 0.20 floor. The band is a coin flip
# BEFORE any behavior change: re-dealt at eight `_DEAL_SEED` offsets, the
# engine at base `b0a6a4e` (pre-N-DRAWLOOSE) breaches its OWN floor on 2 of 8
# — measured here, not quoted: 0.1801, 0.1914, 0.2013, 0.2030, 0.2053, 0.2069,
# 0.2077, 0.2098. Paired against this tip over the same eight deals the effect
# is mean -0.0003 with the sign flipping (3 down, 3 up, 2 exactly equal). One
# reading at `_ARRIVAL_N` therefore cannot tell base from tip, and a red here
# at that N is under-sampling rather than a fit failure.
#
# WHY ESCALATING IS HONEST HERE. `_deal_spots` extends ONE seeded stream, so
# the larger sample is a strict superset of the smaller and the first
# `_ARRIVAL_N` spots produce identical decisions — this is more of the same
# estimator, not a different one. Band VALUES are untouched (frozen to W4-b);
# only the SAMPLE moves.
#
# MEASURED at `_STABLE_ARRIVAL_N` (fish n_arrival = 33636), fish 0.33×pot:
# 0.2065 at this tip, 0.2122 on the base engine — the level is inside the band
# either way. Across four deal seeds at this N the tip reads 0.2057-0.2107 (vs
# 0.1933 at `_ARRIVAL_N`), i.e. the estimator has converged to ~0.208 ± 0.003
# where the throughput reading swings by ±0.012.
#
# ⚠️ DISCLOSED, not laundered: at the stable sample this slice does shift the
# fish's small-price fold rate DOWN by ~0.006 (0.2122 -> 0.2065) — small, but
# consistent in sign at large n, which is why the tip breaches the throughput-N
# floor on 5 of those 8 deals against base's 2 of 8. The level still clears the
# floor; the margin left is only ~0.006 (≈2.6 SE at this n), so the next thing
# that nudges fish small-price defence down will land BELOW the floor at the
# stable sample too — and that is a fit question for the owner, not a sampling
# one. The thin band is filed as `N-FISHFLOOR` (re-derive at W4-b); it is NOT
# fixed by widening the band here.
#
# KNOWN BLIND SPOT, inherited from the precedent: breach-only escalation never
# re-measures a row that reads in-band at the throughput N, so a true stable-n
# breach can pass silently there (the delta-review MED recorded at
# `test_personas_postflop.py:5682-5695`, which is why the AF leg moved to
# assert-at-stable-always). Kept breach-only deliberately: it is the named
# precedent, and it leaves the three non-breaching rows byte-unchanged in
# behavior instead of putting every row on a ~5s re-measure.
_STABLE_ARRIVAL_N = 80000


@functools.cache
def _stable_flop_curve(persona: str) -> tuple[dict[float, float], int]:
    """(flop fold curve, n_arrival) for one persona at `_STABLE_ARRIVAL_N`.

    Memoized, so a second breaching row for the same persona is free."""
    pack = load_persona_packs()[VillainType(persona)]
    flop, _pure3 = _build_flop_arrival(pack, _deal_spots(_STABLE_ARRIVAL_N))
    curve = _fold_curve(pack, flop, 3, _POT_FLOP, _STACK_START, Street.FLOP, 20260721)
    return curve, len(flop)


@pytest.mark.parametrize("persona,frac,lo,hi,src", FLOP_BANDS)
def test_t4_flop_absolute_band(fold_curves, persona, frac, lo, hi, src):
    rate = fold_curves[persona]["flop"][frac]
    if not (lo <= rate <= hi):
        stable, n_stable = _stable_flop_curve(persona)
        assert lo <= stable[frac] <= hi, (
            f"{persona} flop {frac}×pot fold {rate:.3f} (N={_ARRIVAL_N}) breached and "
            f"the stable-sample re-measure {stable[frac]:.4f} "
            f"(N={_STABLE_ARRIVAL_N}, n_arrival={n_stable}) confirms it — "
            f"outside [{lo},{hi}] ({src})"
        )


# --------------------------------------------------------------- manual inspection


def print_curves() -> None:
    """Print the per-persona × per-street × per-size fold curves for the manual
    pre-fix-shape check (T5). Confirms the harness captures the current leak:
    the station is ~flat across sizes and the fish under-folds at the overbet.
    Not a test — call from a REPL or `python -m tests.test_arrival_range_ftc`."""
    packs = load_persona_packs()
    spots = _deal_spots(_ARRIVAL_N)
    a = _Arrival()
    for persona in ALL_PERSONAS:
        pack = packs[VillainType(persona)]
        flop, _ = _build_flop_arrival(pack, spots)
        a.flop[persona] = flop
        rng = random.Random(4001)
        turn = [
            s for s in flop
            if _continues_call(pack, rng, s[0], s[1][:3], _POT_FLOP, _STACK_START, Street.FLOP)
        ]
        a.turn[persona] = turn
        rng = random.Random(4002)
        a.river[persona] = [
            s for s in turn
            if _continues_call(pack, rng, s[0], s[1][:4], a.pot_turn, a.stack_turn, Street.TURN)
        ]
    header = "  ".join(f"{f}x" for f in FLOP_FRACS)
    for persona in ALL_PERSONAS:
        pack = packs[VillainType(persona)]
        print(f"\n{persona}")
        for street, (spots_, sl, pot, stack, seed) in {
            "flop": (a.flop[persona], 3, _POT_FLOP, _STACK_START, 20260721),
            "turn": (a.turn[persona], 4, a.pot_turn, a.stack_turn, 5000),
            "river": (a.river[persona], 5, a.pot_river, a.stack_river, 6000),
        }.items():
            street_enum = {"flop": Street.FLOP, "turn": Street.TURN, "river": Street.RIVER}[street]
            c = _fold_curve(pack, spots_, sl, pot, stack, street_enum, seed)
            row = "  ".join(f"{c[f]:.3f}" for f in FLOP_FRACS)
            print(f"  {street:5s} n={len(spots_):4d}  {header}   {row}")


if __name__ == "__main__":
    print_curves()
